website/models.py
# Import the necessary modules
from website import db
from flask_login import UserMixin

# Define a Recipe class, representing a recipe with a title, category, ingredients, instructions, and author
class Recipe(db.Model):
    # Define the columns of the Recipe table
    id = db.Column(db.Integer, primary_key=True)  # unique identifier for the recipe
    instructions = db.Column(db.String(1000))    # instructions for cooking the recipe
    ingredients = db.Column(db.String(1000))     # ingredients required for the recipe
    title = db.Column(db.String(30))             # title of the recipe
    category = db.Column(db.String(30))          # category of the recipe
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False) # foreign key to the User table
    author = db.relationship('User', backref=db.backref('my_recipes', lazy=True)) # relationship with the User class
    user = db.relationship('User', backref='recipes') # relationship with the User class

    # Define the string representation of a Recipe object
    def __repr__(self):
        return f"Recipe('{self.title}', '{self.category}', '{self.ingredients}', '{self.instructions}')"

# Define a User class, representing a user with an email, password, and first name
class User(db.Model, UserMixin):
    # Define the columns of the User table
    id = db.Column(db.Integer, primary_key=True)   # unique identifier for the user
    email = db.Column(db.String(150), unique=True) # email address of the user
    password = db.Column(db.String(150))           # password of the user
    first_name = db.Column(db.String(150))         # first name of the user

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager


db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config["SECRET_KEY"] = 'andreivince'
    app.config["SQLALCHEMY_DATABASE_URI"] = f'sqlite:///{DB_NAME}'
    db.init_app(app)
    
    
    from .views import views
    from .auth import auth

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    
    from .models import User, Recipe

    create_database(app)
    
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))
    
    return app
        
def create_database(app):
    with app.app_context():
        if not path.exists('website/' + DB_NAME):
            db.create_all()
            print("Create Database!")

website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User, Recipe
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
from flask import Flask, render_template, request, redirect, url_for, flash, get_flashed_messages



auth = Blueprint('auth', __name__)

@auth.route('/search', methods=["GET", "POST"])
@login_required
def search():
    recipes = []
    if request.method == "POST":
        searchBar = request.form.get("searchBar")
        recipes = Recipe.query.filter(Recipe.title.contains(searchBar)).all()

    return render_template("search.html", user=current_user, recipes=recipes)


@auth.route('/create', methods=["GET", "POST"])
@login_required
def create():
    if request.method == 'POST':
        title = request.form.get('title')
        category = request.form.get('category')
        ingredients = request.form.get('ingredients')
        instructions = request.form.get('instructions')
        author = request.form.get('author')

        new_recipe = Recipe(title=title, category=category, ingredients=ingredients, instructions=instructions, author=current_user)
        db.session.add(new_recipe)
        db.session.commit()

        flash('Recipe created!', category='success')
        recipe_id = new_recipe.id
        return redirect(url_for('views.home'))

    return render_template("create.html", user=current_user)





@auth.route('/about')
def about():
    return render_template("about.html", user=current_user) 
   

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == "POST":
        email = request.form.get("email")
        password = request.form.get("password")
        
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash("Logged in!!", category="success")
                login_user(user, remember=True)
                return redirect(url_for("views.home"))
            else:
                flash("Try again!", category="error")
        else:
            flash("Email doesn't exist!!", category="error")
    return render_template("login.html", user=current_user)

            
@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == "POST":
        email = request.form.get("email")
        first_name = request.form.get("firstName")
        password1 = request.form.get("password1")
        password2 = request.form.get("password2")
        
        user = User.query.filter_by(email=email).first()
        if user:
            flash("Email already exist!!", category="error")
        

        
        if len(email) < 4:
            flash("Email Incorrect", category="error")
        elif len(first_name) < 2:
            flash("Name must be greater than 2 characters", category="error")
        elif password1 != password2:
            flash("Passwords don\'t match", category="error")
        elif len(password1) < 7:
            flash("Passwords must be at least 7 characters", category="error")
        else:
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            flash("Account created", category="success")
            return redirect(url_for('views.home'))
            
    
    return render_template("sign_up.html", user=current_user)

# Views of the bar
# line 8 is collecting data
#Message flashing import flash

@auth.route('/delete/<int:recipe_id>', methods=['POST'])
@login_required
def delete_recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    if recipe.user == current_user:
        db.session.delete(recipe)
        db.session.commit()
        flash('Recipe deleted!', category='success')
    else:
        flash('You can only delete your own recipes!', category='error')
    return redirect(url_for('views.home'))

website/views.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user
from .models import Recipe, User
from website import db


views = Blueprint('views', __name__)

@views.route('/')
@login_required
def home():
    recipes = Recipe.query.all()

    return render_template("home.html", user=current_user, recipes=recipes)

@views.route("/recipe/<int:recipe_id>")
@login_required
def recipe(recipe_id):
    recipe = Recipe.query.get_or_404(recipe_id)
    return render_template("recipe.html", user=recipe.user, recipe=recipe)

website/templates/about.html
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css') }}">

{% extends "base.html" %}
{% block title %}About Us{% endblock %}

{% block content%}
        <h1 class="title_home">ShareRecipe<h1>
        <div class="intro_home"> 
            <p>Welcome to RecipeShare, the perfect web application for food lovers! With RecipeShare, you can discover new recipes, share your favorite ones. Our easy-to-use platform allows you to browse through a vast collection of recipes uploaded by other users.</p>
            <p>Whether you're looking for a quick and easy recipe for your busy weeknights or want to impress your guests with a fancy dinner, RecipeShare has got you covered. You can find recipes for all occasions and tastes, from classic comfort food to exotic international dishes. Plus, you can also upload your own recipes and share them with our community of food enthusiasts.</p>
            <p>So what are you waiting for? Join the RecipeShare community today and start sharing your love for food!</p>
        </div>
        <div class="welcome_button">
            <a href="{{ url_for('auth.sign_up') }}" class="btn btn-primary btn-lg" role="button">Start Here</a>
        </div>


{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"  crossorigin="anonymous"   />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous"/>
    <link rel="icon" type="image/x-icon" href="website/assets/AV.ico">
    <title>{% block title %}ShareRecipe{% endblock %}</title> 
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar"> 
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbar">
            <div class="navbar-nav">
                {% if user.is_authenticated %}
                <a class="nav-item nav-link" id="home" href="/">Home</a>
                <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                {%else%}
                <a class="nav-item nav-link" id="about" href="/about">About Us</a>
                <a class="nav-item nav-link" id="login" href="/login">Login</a>
                <a class="nav-item nav-link" id="signIp" href="/sign-up">Sign Up</a>
                {%endif%}
            </div>
        </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
        {% for category, message in messages %}
        {% if category == "error"%}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{message}}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %}
        {% endfor %}
    {% endif %}
    {% endwith %}

    <div class="container">
        {% block content%}
        
        {% endblock %}
    </div>


    <script
    src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"
  ></script>
  <script
    src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"
  ></script>
  </body>
</html>

website/templates/create.html
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/create.css') }}">

{% extends "base.html" %}
{% block title %}Your Recipe{% endblock %}

{% block content%}
    <div class="your_recipe">
        <h1>Add Your Recipe</h1>
        <div class="forms_recipe">
            <form method="POST" action="{{ url_for('auth.create') }}">
                <input class="form-control" type="text" name="title" placeholder="Title" required>
                <input class="form-control" type="text" name="category" placeholder="Category" required>
                <textarea class="form-control" name="ingredients" placeholder="Ingredients" required></textarea>
                <textarea class="form-control" name="instructions" placeholder="Instructions" required></textarea>
                <button class="btn btn-primary" type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock %}

website/templates/home.html
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/home.css') }}">

{% extends "base.html" %}
{% block title %}Home{% endblock %}

{% block content%}
        <div class="title_add">
            <h1 class="title_home">ShareRecipe<h1> 
                <a href="{{ url_for('auth.create') }}" class="btn btn-primary btn-lg" role="button">+</a>
                <a href="{{ url_for('auth.search') }}" class="btn btn-primary btn-lg" role="button">?</a>
            </div>
        {% for recipe in recipes %}
        <a href="{{ url_for('views.recipe', recipe_id=recipe.id) }}" class="recipe-link">
            <p class="name_recipe">{{ recipe.title }}</p>
        </a>
        
        {% endfor %}

{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
# Exact the same thing but with the overwrite code
{% block content %}
<form method="POST">
    <br/>
    <br/>
    <h3 align="center">Login</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email">
    </div>
    <div class="form-group">
        <label for="password">Password</label>
        <input type="password" class="form-control" id="password" name="password" placeholder="Enter Password">
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Login</button>
</form>
{% endblock %}

website/templates/recipe.html
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/recipe.css') }}">


{% extends "base.html" %}
{% block title %}{{ recipe.title }}{% endblock %}

{% block content %}
  <div class="recipe">
    <h1 class="title_recipe">{{ recipe.title }}</h1>
    <p class="author_recipe">Posted by: {{ recipe.user.first_name }}</p>
    <p class="label_recipe">Category:</p>
    <p>{{ recipe.category }}</p>
    <p class="label_recipe">Ingredients:</p>
    <p class="user_recipe">{{ recipe.ingredients }}</p>
    <p class="label_recipe">Instructions:</p>
    <p class="user_recipe">{{ recipe.instructions }}</p>
    {% if recipe.user == current_user %}
    <form action="{{ url_for('auth.delete_recipe', recipe_id=recipe.id) }}" method="post">
        <button type="submit" class="btn btn-danger">Delete Recipe</button>
    </form>
    {% endif %}
</div>
{% endblock %}

website/templates/search.html
<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/search.css') }}">


{% extends "base.html" %}
{% block title %}Search{% endblock %}

{% block content %}
  <div class="search"> 
    <h1>Search</h1>
    <form method="POST">
        <input type="text" class="form-control" id="searchBar" name="searchBar" placeholder="Search for Recipe">
    </form>
    {% if recipes %}
            <div class="recipe-titles">
                {% for recipe in recipes %}
                  <a href="{{ url_for('views.recipe', recipe_id=recipe.id) }}">
                  <p>{{ recipe.title }}</p>
                  </a>
                {% endfor %}
            </div>
            {% endif %}
            
  </div>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}
<form method="POST">
    <br/>
    <br/>
    <h3 align="center"> Sign Up</h3>
    <div class="form-group">
        <label for="email">Email Address</label>
        <input type="email" class="form-control" id="email" name="email" placeholder="Enter Email">
    </div>
    <div class="form-group">
        <label for="firstName">First Name</label>
        <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Enter First Name">
    </div>
    <div class="form-group">
        <label for="password1">Password</label>
        <input type="password" class="form-control" id="password1" name="password1" placeholder="Enter Password">
    </div>
    <div class="form-group">
        <label for="password2">Passoword (Confirm)</label>
        <input type="password" class="form-control" id="password2" name="password2" placeholder="Confirm Password">
    </div>
    <br/>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>
{% endblock %}